name: Publish Python distribution to PyPI

on:
  release:
    types: [released]

jobs:
  publish-pypi-package:
    name: Publish Python distribution to PyPI.
    runs-on: ubuntu-latest

    environment:
      name: release
      url: https://pypi.org/project/pgqueuer/

    permissions:
      id-token: write

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Ensures tags are also fetched

      - name: Set up Python 3.10.
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install release dependencies.
        run: python3 -m pip install build twine setuptools_scm

      - name: Build package.
        run: python3 -m build . --sdist --wheel --outdir dist/

      - uses: pypa/gh-action-pypi-publish@release/v1

  publish-docker-image:
    needs: [publish-pypi-package]
    name: Publish docker image
    runs-on: ubuntu-latest

    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to the Container registry
        uses: docker/login-action@@v3
        with:
          registry: https://ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_PAT }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ghcr.io/janbjorge/pgq-prometheus-service:${{ github.ref_name }}
